# Generated by Django 4.1.5 on 2023-02-11 17:21

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True, verbose_name='phone')),
                ('teg', models.CharField(choices=[('ВИП', 'ВИП'), ('Не беспокоить', 'Не беспокоить'), ('Обычный', 'Обычный')], default='Обычный', max_length=15, verbose_name='Тег')),
                ('code_operator', models.IntegerField(verbose_name='Код моб. оператора')),
                ('time_zone', models.IntegerField(choices=[(1, '-10'), (2, '-9'), (3, '-8'), (4, '-7'), (5, '-6'), (6, '-5'), (7, '-4'), (8, '-3'), (9, '-2'), (10, '-1'), (11, '0'), (12, '+1'), (13, '+2'), (14, '+3'), (15, '+4'), (16, '+5'), (17, '+6'), (18, '+7'), (19, '+8'), (20, '+9'), (21, '+10'), (22, '+11'), (23, '+12'), (24, '+13'), (25, '+14')], default=14, verbose_name='UTC')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['phone'],
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_mailing', models.DateTimeField(verbose_name='Дата начала рассылки')),
                ('finish_mailing', models.DateTimeField(verbose_name='Дата окончания рассылки')),
                ('text_message', models.TextField(blank=True, verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_maling', models.DateTimeField(verbose_name='Дата отправки')),
                ('status', models.IntegerField(default=0, verbose_name='Статус')),
                ('id_clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primefield.clients', verbose_name='id Клиента')),
                ('id_mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primefield.mailing', verbose_name='id Рассылки')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
