# Generated by Django 4.1.5 on 2023-02-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primefield', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0, verbose_name='Статус')),
                ('mailings_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primefield.mailing')),
            ],
        ),
    ]
